# Generated by Django 4.2.25 on 2025-10-24 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoDont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('do', 'Do'), ('dont', "Don't")], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('dodont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='journal.dodont')),
            ],
            options={
                'verbose_name_plural': 'Daily entries',
                'ordering': ['-date', 'dodont__order'],
                'unique_together': {('dodont', 'date')},
            },
        ),
    ]
