# Generated by Django 4.2.25 on 2025-10-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='text_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
